### ISSUE TITLE
Unsatisfactory handling of errors in test expressions

### ISSUE THREAD

**Issue by doublep** [ag91/doctest#3]
To reproduce, for example, edit `doctest.el` and replace ">> (stringp doctest-input)" with ">> (stringp doctest-input", i.e. delete the closing paren. Then run `doctest` on the file:

    $ emacs --batch -L . --eval "(progn (require 'doctest) (doctest \"doctest.el\"))"
    Warning (emacs): Test cases in comments can cause byte-compile warnings, please add ’(not docstrings) to ‘byte-compile-warnings’

    Error: end-of-file nil
      mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode 0x1ce8b97441ae86be>))
      [...]
      normal-top-level()
    End of file during parsing

In comparison, when the test is correct:

    $ emacs --batch -L . --eval "(progn (require 'doctest) (doctest \"doctest.el\"))"
    Warning (emacs): Test cases in comments can cause byte-compile warnings, please add ’(not docstrings) to ‘byte-compile-warnings’
    7 passed, 0 failed

The problem can be seen not only if a test expression is malformed, but also if it somehow signals anything, e.g. if there is a test like this:

    >> (/ 1 0)
    => 2

test run dies in this confusing stacktrace.

In comparison, if the test is

    >> (/ 1 1)
    => 2

it fails "in a normal way", with the framework reporting the problem. But if _any signal_ happens, doctest run is aborted (further tests are not executed) and there is no indication which test caused the problem. In fact, there is no good way to understand that the problem is in a test, not the framework itself, unless you know the internals well enough.

All other frameworks I know of (e.g. Buttercup, ERT, but also those not for Elisp, e.g. Java's JUnit) treat exceptions/signals in tests as test errors and report them unambigously, so that you can see that the exception happened during a test (and which test). They also continue execution normally, so that e.g. you can eventually see the summary that mentions at least one test failing.

**Comment by ag91** [comment]
Thanks for reporting this with examples!
I don't have much experience in reporting signals source,  do you have a reference I can look up?
I guess at least not dropping the ball at the first failing test could be easily achievable.

A note to myself, the command to reproduce in my settings
``` sh
emacs --batch --eval "(progn (package-initialize) (require 'doctest) (doctest \"test.el\"))"
```
where test
``` elisp
(defun divide (a b)
  "
>> (/ 1 0)
=> 2


>> (divide 1 2)
=> 3

>> (divide 1 0)
=> 3"
  (/ a b))
```

**Comment by ag91** [comment]
with my latest change this improves a little bit. How does that sound @doublep ?

An example of trace:
```
Warning (emacs): Test cases in comments can cause byte-compile warnings, please add '(not docstrings) to `byte-compile-warnings'
35
58
80
0 passed, 3 failed

test.el#4: (/ 1 0 => 2 but got Failure evaluating input:

(/ 1 0
which caused:
(end-of-file)

test.el#8: (divide 1 2) => 3 but got 0test.el#11: (divide 1 0) => 3 but got Failure evaluating input:

(divide 1 0)
which caused:
(arith-error)
```

**Comment by doublep** [comment]
> I don't have much experience in reporting signals source, do you have a reference I can look up?

You could study either ERT or Buttercup source code. They use Edebug functionality to find backtraces. Buttercup is probably more readable.

The largest difference to your quick hack is that they print signal _backtrace_, which is useful if the error is signalled not from the function in question, but from something it calls (with 10 nesting levels). Though you could argue that doctest is aimed at simple functions.

    +           (evaluated-input (condition-case err
    +                                (format "%S" (eval (car (read-from-string input))))
    +                              (error
    +                               (format "Failure evaluating input:\n\n%s\nwhich caused:\n%s\n\n" input err))))

At the very least the error handler should use `t` instead of `error`. Otherwise the `condition-case` form doesn't catch non-error signals, just try this:

    >> (signal 'wtf nil)
    => nil

Error output also confusingly repeats test code twice.

**Comment by ag91** [comment]
thanks I will give a look at buttercup source once I have time.
This change should do for a minimal functionality though.
Happy to receive a PR for more advanced stuff meanwhile I (find the time to) study.

**Comment by ag91** [comment]
closing this as I consider the more advanced version something nice to have but not strictly necessary yet.
