### ISSUE TITLE
Test results are printed only after all tests have been completed

### ISSUE THREAD

**Issue by doublep** [ag91/doctest#4]
To reproduce, add this test to a file a few times:

    >> (sleep-for 1.0)
    => t

and run it (noninteractively). A user would expect that approximately every second the framework would print information about the next failure (`sleep-for` returns nil, so all these tests will fail). Instead, after several seconds the framework prints all the information at once. Interactive behavior appears to be similar.

While probably not important in most cases, it can be annoying if you have a lot of (moderately) slow tests, as then you have no idea about the progress.

Also, as far as progress notification is concerned, it would be nice for the framework to optionally print something for passing tests too. E.g. there could be a variable `doctest-verbose` or something like that to control the behavior.

**Comment by ag91** [comment]
Thanks for suggesting this improvement. My latest commit should provide that. Please check the new defcustom or the commit log for an explanation.
