### ISSUE TITLE
Possibility to clump together tests from several files

### ISSUE THREAD

**Issue by doublep** [ag91/doctest#7]
Currently (this is still unpublished work) when I run testing from Eldev on a project with two files I get this:

    1 passed, 0 failed
    1 passed, 0 failed

This means that test in each of the two files are run separately, with counts being reset after each file and summary being printed. This is problematic for two reasons: 1) this is unlike every other framework I know; 2) the summary doesn't even mention which file was executed, so splitting it is kind of pointless, since you don't know which "subsummary" corresponds to which file anyway.

I'm not opening a PR here, because I can see several different ways of solving this, but neither is a clear winner, so I want to discuss first.

Currently the "highest level" entry point is function `doctest`. However, by design it runs on a single buffer/file, resets counters and prints summary itself. At least for backward compatibility I propose to keep this behavior.

However, there should be a way to mark a testsuite that consists of multiple buffers somehow.

Some possibilities:

* Have another function `doctest-<NAME-MISSING>` that accepts multiple files and considers them a single suite. Existing `doctest` would then just call this function with a single file.

* Have a global variable, e.g. sth. like `doctest-inside-suite`, initially nil. If bound to non-nil, function `doctest` doesn't reset the counters and doesn't print the summary, i.e. considers itself a part of ongoing testsuite. However, we then also need to make public the counter-resetting and summary-printing functions public. Usage would look something like this:

      (let ((doctest-inside-suite t))
        (doctest-reset-state)
        (dolist (file all-files)
          (doctest file))
        (doctest-print-summary))

* Optionally extending the above: add a function like e.g. `doctest-composite-suite` that "hides" as internals first and last steps (advantages: no need to make a lot of things public, they can stay package-private). Usage would look like:

      (doctest-composite-suite (lambda ()
                                 (dolist (file all-files)
                                   (doctest file)))

Or would you prefer some other way? I can create a PR, just pick some approach.

**Comment by ag91** [comment]
Good point, I didn't need this yet because my extension are usually a single file.
I would go for a separate function for this, so your first option because this is a completely new feature.

Thinking about it, the design issue seems to be that `doctest` doesn't return data but just prints out something:
if you were to receive an output like `'(:file "somepath/code.el" :pass 1 :fail 1 :errors ())`,
your new use case would be simple to implement being just a view of the data.

**Comment by doublep** [comment]
> Thinking about it, the design issue seems to be that doctest doesn't return data but just prints out something

Well, changing that would be backward-incompatible (even if there is unlikely to be any code depending on this). Also, as it is now, users can query the current test counts using the recently added `doctest-state` (or previously by accessing package-private variables). If this use scenario is to be retained, we need counts to stay as a global state, otherwise you wouldn't be able to query them after the fact, you'd _have_ to use the return value. And this means there has to be a well-defined point where counts are reset to zero.

**Comment by ag91** [comment]
Okay, I think we can go with your first proposal to add a new function running a suite then.
I am not so concerned about backward-compatibility because we can always deprecate current functions,
but we don't need that yet if there are ways around that are nice as well :)

**Comment by doublep** [comment]
Sorry for long silence, don't have much time for Elisp stuff.

I now noticed a really weird piece of code:

    (defun doctest--reset-state ()
      "Reset doctest's current state."
      (when (eq major-mode 'emacs-lisp-mode) (eval-buffer))
      ...

First, it is semantically a wrong place. Why does `...reset-state`, of all things, evaluate the buffer? Second, I'm not sure it should be done at all, at least when non-interactive. Yeah, it provides all the function definitions which are used in the test expressions, but evaluating the whole buffer potentially has a lot of consequences...

Is it fine if the new function _relies_ on the caller to provide all the function definitions (with this being mentioned in the documentation, of course)? For example, the caller could `require` necessary Elisp features, which may or may not be byte-compiled. In comparison, `eval-buffer` always results in non-byte-compiled definitions.

**Comment by ag91** [comment]
well spotted! That must have been a shortcut: it is done also for [doctest-defun](https://github.com/ag91/doctest/blob/master/doctest.el#L159) and also there seems unnecessary.
I suspect that for stateful code, you may find useful to reset all vars to their init value via eval-buffer but I would probably add some sort of `defcustom` to enable this unsafe behavior on demand.

That seems fine to me, I could provide different default functions that `eval-buffer` or evaluate only the minimum necessary code to make user's life easier.

**Comment by doublep** [comment]
Implemented in PR #8.
